// <auto-generated/>
using System;
using Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models;

namespace Clean.Microservice.Serverless.Core.UseCases.CreateCustomer.V1.Models
{
    /// <summary>
    /// Define create customer response data.
    /// </summary>
    public class CreateCustomerResponseModel : IResponseModel
    {
        /// <summary>
        /// Customer id created.
        /// </summary>
        public virtual Guid Id { get; set; }
    }
}
