// <auto-generated/>
using Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models;

namespace Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models.V1
{
    /// <summary>
    /// Define compound value.
    /// </summary>
    public class CompoundValueModel : IModel
    {
        /// <summary>
        /// Value.
        /// </summary>
        public virtual decimal Value { get; set; }

        /// <summary>
        /// Symbol.
        /// </summary>
        /// <example>%</example>
        public virtual string Symbol { get; set; }

        /// <summary>
        /// Formatted value with symbol.
        /// </summary>
        /// <example>5%</example>
        public virtual string Formatted { get; set; }
    }
}