// <auto-generated/>
namespace Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models.V1
{
    /// <summary>
    /// Define compound value with period.
    /// </summary>
    public class CompoundValuePeriodModel : CompoundValueModel
    {
        /// <summary>
        /// Period of a certain amount, such as interest per month.
        /// </summary>
        /// <example>a.m.</example>
        public virtual string Period { get; set; }
    }
}