// <auto-generated/>
namespace Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models.V1
{
    /// <summary>
    /// Define currency data.
    /// </summary>
    public class CurrencyModel
    {
        /// <summary>
        /// Iso code.
        /// </summary>
        /// <example>BRL</example>
        public virtual string Iso { get; set; }

        /// <summary>
        /// Currency symbol.
        /// </summary>
        /// <example>R$</example>
        public virtual string Symbol { get; set; }
    }
}