// <auto-generated/>
namespace Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models.V1
{
    /// <summary>
    /// Define the date month.
    /// </summary>
    public class DateMonthModel : IResponseModel
    {
        /// <summary>
        /// Abbreviated month.
        /// </summary>
        /// <example>JAN</example>
        public virtual string Abbreviated { get; set; }

        /// <summary>
        /// Month number.
        /// </summary>
        public virtual int Number { get; set; }

        /// <summary>
        /// Month name.
        /// </summary>
        /// <example>Janeiro</example>
        public virtual string Name { get; set; }

        /// <summary>
        /// Month builder.
        /// </summary>
        /// <param name="month">Month number.</param>
        /// <returns>Instance of <see cref="DateMonthModel"/>.</returns>
        public static DateMonthModel Builder(int month)
        {
            return new DateMonthModel
            {
                Abbreviated = GetAbbreviatedMonth(month),
                Name = GetMonthName(month),
                Number = month
            };
        }

        private static string GetAbbreviatedMonth(int month)
        {
            switch (month)
            {
                case 1:
                    return DateMonthModelFields.MONTH_JANUARY_ABBREVIATED;
                case 2:
                    return DateMonthModelFields.MONTH_FEBRUARY_ABBREVIATED;
                case 3:
                    return DateMonthModelFields.MONTH_MARCH_ABBREVIATED;
                case 4:
                    return DateMonthModelFields.MONTH_APRIL_ABBREVIATED;
                case 5:
                    return DateMonthModelFields.MONTH_MAY_ABBREVIATED;
                case 6:
                    return DateMonthModelFields.MONTH_JUNE_ABBREVIATED;
                case 7:
                    return DateMonthModelFields.MONTH_JULY_ABBREVIATED;
                case 8:
                    return DateMonthModelFields.MONTH_AUGUST_ABBREVIATED;
                case 9:
                    return DateMonthModelFields.MONTH_SEPTEMBER_ABBREVIATED;
                case 10:
                    return DateMonthModelFields.MONTH_OCTOBER_ABBREVIATED;
                case 11:
                    return DateMonthModelFields.MONTH_NOVEMBER_ABBREVIATED;
                default:
                    return DateMonthModelFields.MONTH_DECEMBER_ABBREVIATED;
            }
        }

        private static string GetMonthName(int month)
        {
            switch (month)
            {
                case 1:
                    return DateMonthModelFields.MONTH_JANUARY;
                case 2:
                    return DateMonthModelFields.MONTH_FEBRUARY;
                case 3:
                    return DateMonthModelFields.MONTH_MARCH;
                case 4:
                    return DateMonthModelFields.MONTH_APRIL;
                case 5:
                    return DateMonthModelFields.MONTH_MAY;
                case 6:
                    return DateMonthModelFields.MONTH_JUNE;
                case 7:
                    return DateMonthModelFields.MONTH_JULY;
                case 8:
                    return DateMonthModelFields.MONTH_AUGUST;
                case 9:
                    return DateMonthModelFields.MONTH_SEPTEMBER;
                case 10:
                    return DateMonthModelFields.MONTH_OCTOBER;
                case 11:
                    return DateMonthModelFields.MONTH_NOVEMBER;
                default:
                    return DateMonthModelFields.MONTH_DECEMBER;
            }
        }
    }
}