// <auto-generated/>
namespace Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models.V1
{
    /// <summary>
    /// Define the time of a date.
    /// </summary>
    public class DateTimeModel : DateModel
    {
        /// <summary>
        /// Date hour.
        /// </summary>
        public virtual int Hour { get; set; }

        /// <summary>
        /// Date minute.
        /// </summary>
        public virtual int Minute { get; set; }

        /// <summary>
        /// Date second.
        /// </summary>
        public virtual int Second { get; set; }

        /// <summary>
        /// Formatted time.
        /// </summary>
        /// <example>15:32:12</example>
        public virtual string FormattedTime { get; set; }
    }
}