// <auto-generated/>
using System;

namespace Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models.V1
{
    /// <summary>
    /// Define the data of a date.
    /// </summary>
    public class DateModel : IModel
    {
        /// <summary>
        /// Full date.
        /// </summary>
        public virtual DateTimeOffset FullDate { get; set; }

        /// <summary>
        /// Short date.
        /// </summary>
        /// <example>23-01-2019</example>
        public virtual string ShortDate { get; set; }

        /// <summary>
        /// Date day.
        /// </summary>
        public virtual int Day { get; set; }

        /// <summary>
        /// Date month.
        /// </summary>
        public virtual DateMonthModel Month { get; set; }

        /// <summary>
        /// Date year.
        /// </summary>
        public virtual DateYearModel Year { get; set; }
    }
}