//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models.V1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DateMonthModelFields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateMonthModelFields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clean.Microservice.Serverless.UseCases.Models.V1.DateMonthModelFields", typeof(DateMonthModelFields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        internal static string MONTH_APRIL {
            get {
                return ResourceManager.GetString("MONTH_APRIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abr.
        /// </summary>
        internal static string MONTH_APRIL_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_APRIL_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        internal static string MONTH_AUGUST {
            get {
                return ResourceManager.GetString("MONTH_AUGUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ago.
        /// </summary>
        internal static string MONTH_AUGUST_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_AUGUST_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezembro.
        /// </summary>
        internal static string MONTH_DECEMBER {
            get {
                return ResourceManager.GetString("MONTH_DECEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dez.
        /// </summary>
        internal static string MONTH_DECEMBER_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_DECEMBER_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fevereiro.
        /// </summary>
        internal static string MONTH_FEBRUARY {
            get {
                return ResourceManager.GetString("MONTH_FEBRUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeV.
        /// </summary>
        internal static string MONTH_FEBRUARY_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_FEBRUARY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janeiro.
        /// </summary>
        internal static string MONTH_JANUARY {
            get {
                return ResourceManager.GetString("MONTH_JANUARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        internal static string MONTH_JANUARY_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_JANUARY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julho.
        /// </summary>
        internal static string MONTH_JULY {
            get {
                return ResourceManager.GetString("MONTH_JULY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        internal static string MONTH_JULY_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_JULY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junho.
        /// </summary>
        internal static string MONTH_JUNE {
            get {
                return ResourceManager.GetString("MONTH_JUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        internal static string MONTH_JUNE_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_JUNE_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Março.
        /// </summary>
        internal static string MONTH_MARCH {
            get {
                return ResourceManager.GetString("MONTH_MARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        internal static string MONTH_MARCH_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_MARCH_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        internal static string MONTH_MAY {
            get {
                return ResourceManager.GetString("MONTH_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai.
        /// </summary>
        internal static string MONTH_MAY_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_MAY_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembro.
        /// </summary>
        internal static string MONTH_NOVEMBER {
            get {
                return ResourceManager.GetString("MONTH_NOVEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        internal static string MONTH_NOVEMBER_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_NOVEMBER_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outubro.
        /// </summary>
        internal static string MONTH_OCTOBER {
            get {
                return ResourceManager.GetString("MONTH_OCTOBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string MONTH_OCTOBER_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_OCTOBER_ABBREVIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        internal static string MONTH_SEPTEMBER {
            get {
                return ResourceManager.GetString("MONTH_SEPTEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string MONTH_SEPTEMBER_ABBREVIATED {
            get {
                return ResourceManager.GetString("MONTH_SEPTEMBER_ABBREVIATED", resourceCulture);
            }
        }
    }
}
