// <auto-generated/>

using System;

namespace Clean.Microservice.Serverless.SharedKernel.Core.UseCases.Models.V1
{
    /// <summary>
    /// Define the year of a date.
    /// </summary>
    public class DateYearModel : IResponseModel
    {
        /// <summary>
        /// Abbreviated year. Eg: 19
        /// </summary>
        public virtual int Abbreviated { get; set; }

        /// <summary>
        /// Full year. Eg: 2019
        /// </summary>
        public virtual int Full { get; set; }

        /// <summary>
        /// Year builder.
        /// </summary>
        /// <param name="fullYear">Full year.</param>
        /// <returns>Instance of <see cref="DateYearModel"/>.</returns>
        public static DateYearModel Builder(int fullYear)
        {
            return new DateYearModel
            {
                Abbreviated = Convert.ToInt32(fullYear % 100),
                Full = fullYear
            };
        }
    }
}