// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "not necessary", Scope = "member", Target = "~M:Clean.Microservice.Serverless.Plugin.Logger.ModalLogger.FormatResponse(System.IO.MemoryStream,System.IO.Stream)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "not necessary", Scope = "member", Target = "~M:Clean.Microservice.Serverless.Plugin.Logger.LoggingHandler.SendAsync(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "not necessary", Scope = "member", Target = "~M:Clean.Microservice.Serverless.Plugin.Logger.Entities.LogWcf.BeforeSendRequest(System.ServiceModel.Channels.Message@,System.ServiceModel.IClientChannel)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "not necessary", Scope = "member", Target = "~M:Clean.Microservice.Serverless.Plugin.Logger.Entities.LogWcf.AfterReceiveReply(System.ServiceModel.Channels.Message@,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "not necessary", Scope = "member", Target = "~M:Clean.Microservice.Serverless.Plugin.Logger.Entities.LogWcf.CreateLog(System.ServiceModel.Channels.Message,System.DateTimeOffset,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "not necessary", Scope = "member", Target = "~M:Clean.Microservice.Serverless.Plugin.Logger.Entities.LogWcf.CreateLog(System.ServiceModel.Channels.Message,System.DateTimeOffset,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "not necessary", Scope = "member", Target = "~M:Clean.Microservice.Serverless.Plugin.Logger.ServerlessLogger.FormatResponse(System.IO.MemoryStream,System.IO.Stream)~System.Threading.Tasks.Task{System.String}")]